name: Electron.Net macOS Build

on:
  push:
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.1
    - name: Install tool
      run: dotnet tool install ElectronNET.CLI -g
    - name: make script executable
      run: chmod +x scripts/build-mac.sh
    - name: Build
      run: scripts/build-mac.sh
      env: 
        GH_TOKEN: ${{secrets.CI_TOKEN}}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
      # Artifact name
        name: mac-build
      # Directory containing files to upload
        path: ./src/HITScheduleMasterPlus/bin/Desktop
